### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by asood123** [Uniswap/sybil-interface#2]
Here is a tracker for what's remaining - both big and small. Feel free to add other things that come up.

- [x] [Ian] Clean data fetching from the graph, so it’s faster / less spotty
- [x] [Ian] Run twitter server in Uniswap lambda (currently in Ians lambda)
- [x] [Ian] Resolve gist vs file in repo
- [x] [Ian] Deploy server for Twitter login (lambda?)
- [x] [Cal] UI: Finalize layout of main page
- [x] [Cal/Aseem/Hayden]: Review final flow with all the actions
- [x] [Ian] Implement final UI for desktop
- [x] [Ian] Implement UI for Mobile
- [x] [Ian] Setup a shared doc for all copy
- [x] [Cal/Aseem/Teo] Review and add to How it works doc
- [x] [Cal/Aseem/Teo] Review and add to FAQ page
- [x] [Ian] Publish app to a non-descript url so we can share externally and get early delegators
- [x] [Ian] Update GitHub README.md for someone to spin it up themselves - does this mean generate own list? or whole verification setup
- [x] [Ian] fix vote counting bug
- [x] [Ian] See if filtering to sybil-only can be done easily
- [x] [Ian] Hide "unlock votes" if they have no UNI 
- [x] [Ian] Add a check to look for the latest tweet from the user before opening window (useful when there is a delay and user clicks the button again)
- [x] [Cal] Review tweet copy
- [x] [Aseem/Cal] Review Github Readme
- [x] [Teo] Draft announcement blogpost
- [x] [Teo/Aseem] Review messaging (FAQ, GitHub Docs, blogpost, tweet copy) with Marvin
- [x] [Teo] Find ~5 delegates to prepopulate (they should still go through the flow)

Last step before announcing launch
- [x] [Ian] Connect to sybil.org
- [x] update Infura key to work on this domain

Post-launch
- [ ] Add pagination to show more
- [ ] Explore iframing the flow for easy embedding
- [ ] npm package for consuming versions of the list 
- [ ] github verification 
- [ ] improved twitter login - window popup?

**Comment by asood123** [comment]
Closing this; will start another list to track future changes
